### ISSUE TITLE
build failure on Windows

### ISSUE THREAD

**Issue by mateodelnorte** [digitalinfinity/generator-napi-module#1]
Moving over to here so as not to spam the n-api repo. 

I'm getting a build failure on windows with the following logs. Any ideas?

https://gist.github.com/mateodelnorte/821335aeb1d4e6a4dfdb594f0386dc97

**Comment by mateodelnorte** [comment]
@jasongin

**Comment by digitalinfinity** [comment]
Hi @mateodelnorte - are you using the generated skeleton code? From the log, it looks like you may have some code changes- if so, can you share the snippet corresponding to the first failure in the build logs? It's possible that this is a error in the C++ wrapper and having the snippet will help us repro.

**Comment by jasongin** [comment]
> node-gyp rebuild --msvs_version=2013

Just a guess, but the issue could be due to the use of VS 2013. I think we've only tested with VS 2015 & 2017.

**Comment by mateodelnorte** [comment]
Unfortunately, I've only got 2013 and 2012 at this client. Though that shouldn't really matter, should just be the --msvs_version=xxxx version specification. Is there one I should use which should work?

**Comment by mateodelnorte** [comment]
I get a different set of compile errors when targeting 2015 https://gist.github.com/mateodelnorte/8c49520a883d7fb20ef8be784ac10a9a

**Comment by mateodelnorte** [comment]
https://github.com/nodejs/node-addon-api/issues/56

ok. I was able to build with 2015. I should be good, but I'll ping back at the issue above if I find I need 2013 and can't get past the impasse. Cheers!
